name: Build

on: [push, pull_request]

jobs:

  build:
    name: Build for ${{ matrix.python-version }}
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8']
    steps:
      - uses: actions/checkout@v2
      - name: setup-conda
        uses: s-weigand/setup-conda@v1.0.2
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: 'conda-forge'
      - run: conda --version
      - name: Python info
        shell: bash -l {0}
        run: |
          which python
          python --version
      - run: conda install gdal -c conda-forge
      - name: Install the package
        env:
          CONDA_PREFIX: /usr/share/miniconda
        run: pip install -e .
      - name: Test
        env:
          CONDA_PREFIX: /usr/share/miniconda
        run: |
          python setup.py test
