name: Build

on: [push, pull_request]

jobs:

  build:
    name: Build for (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.6', '3.7', '3.8']
    steps:
      - uses: actions/checkout@v2
      - name: setup-conda
        uses: s-weigand/setup-conda@v1.0.2
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: 'conda-forge'
      - run: conda --version
      - name: Python info
        shell: bash -l {0}
        run: |
          which python
          python --version
      - run: conda install gdal
      - name: Install the package
        env:
          CONDA_PREFIX: /usr/share/miniconda
        run: pip install -e .
      - name: Test
        env:
          CONDA_PREFIX: /usr/share/miniconda
        run: |
          python setup.py test
          pytest --cov --cov-report term --cov-report xml --junitxml=xunit-result.xml
